local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

development:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

# ðŸ‘‡ PRODUCCIÃ“N TAMBIÃ‰N USA DISCO LOCAL
production:
  service: Disk
  root: <%= Rails.root.join("storage") %>